service: telegram-manager
frameworkVersion: '2'

custom: ${file(./configs.yml)}
provider:
  name: aws
  memorySize: 128
  timeout: 300
  stage: ${self:custom.provider.stage}
  runtime: ${self:custom.provider.runtime}
  profile: ${self:custom.provider.profile}
  region: ${self:custom.provider.region}
  role: ${self:custom.provider.role}
  layers: ${self:custom.provider.layers}

functions:
  send:
    handler: handler.send
    events:
      - sqs:
         arn:
          Fn::GetAtt:
            - SendQueue
            - Arn

resources:
  Resources:
    SendQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "telegram-manager-queue"
        VisibilityTimeout: 300
